#ifndef _VERSION_H_
#define _VERSION_H_

#define EREADER_VERSION_NUM 0x00080051
#define EREADER_VERSION_SHORT "0.8"
#define EREADER_VERSION_LONG "0.8.0.81 Built "  __TIME__ " " __DATE__
#define EREADER_VERSION_STR_SHORT "eReader " EREADER_VERSION_SHORT
#define EREADER_VERSION_STR_LONG "eReader " EREADER_VERSION_LONG

#endif
